const test = require('node:test');
const assert = require('node:assert/strict');

const {
  analyzeTextEvidence,
  classifyRepoEvidence,
  renderHtml,
  scoreRepoEvidence,
  summarizeCommits,
  summarizePullRequests,
} = require('../scripts/explore_repo_authorship_signals');

test('analyzeTextEvidence finds explicit repo claims and supervision phrases', () => {
  const evidence = analyzeTextEvidence(`
    This repository contains an AI-generated Lean formalization.
    Generated by the Gauss autoformalization agent, with human supervision.
  `);

  assert.equal(evidence.repoWideClaims.length > 0, true);
  assert.equal(evidence.explicitClaims.length > 0, true);
  assert.equal(evidence.supervisionClaims.length > 0, true);
  assert.deepEqual(evidence.agentLabels, ['gauss']);
});

test('summaries capture attribution signals from PRs and commits', () => {
  const prSummary = summarizePullRequests([
    {
      number: 11,
      title: 'Generated with Claude Code',
      body: 'This project was entirely generated by Claude Code.',
      html_url: 'https://example.com/pr/11',
      created_at: '2026-03-20T00:00:00Z',
      user: { login: 'claude-runner', type: 'User' },
    },
  ]);
  const commitSummary = summarizeCommits([
    {
      sha: '1234567890abcdef',
      html_url: 'https://example.com/commit/123',
      author: { login: 'alice', type: 'User' },
      commit: {
        author: { name: 'Alice', date: '2026-03-20T00:00:00Z' },
        message: 'Generated with Claude Code\n\nCo-Authored-By: Claude <noreply@example.com>',
      },
    },
  ]);

  assert.equal(prSummary.explicitAttributedPrs, 1);
  assert.equal(prSummary.loginAttributedPrs, 1);
  assert.equal(prSummary.agentSignalPrs, 1);
  assert.equal(commitSummary.explicitAttributedCommits, 1);
  assert.equal(commitSummary.coauthoredAgentCommits, 1);
  assert.equal(commitSummary.mentionedAgentCommits, 1);
});

test('classifyRepoEvidence separates AI-explicit from human-led', () => {
  const explicitReadmeSignals = analyzeTextEvidence('This project was entirely generated by Claude Code.');
  const emptySignals = analyzeTextEvidence('');

  const explicitScores = scoreRepoEvidence({
    readmeSignals: explicitReadmeSignals,
    structureSignals: { manifestHits: [], configHits: [], workflowHints: [] },
    prSummary: {
      sampleSize: 10,
      explicitAttributedPrs: 1,
      loginAttributedPrs: 1,
      botAuthoredPrs: 0,
    },
    commitSummary: {
      sampleSize: 10,
      explicitAttributedCommits: 1,
      coauthoredAgentCommits: 0,
      mentionedAgentCommits: 1,
    },
  });

  const explicitClassification = classifyRepoEvidence({
    readmeSignals: explicitReadmeSignals,
    structureSignals: { manifestHits: [], configHits: [], workflowHints: [] },
    prSummary: {
      sampleSize: 10,
      explicitAttributedPrs: 1,
      loginAttributedPrs: 1,
      botAuthoredPrs: 0,
    },
    commitSummary: {
      sampleSize: 10,
      explicitAttributedCommits: 1,
      coauthoredAgentCommits: 0,
      mentionedAgentCommits: 1,
    },
    scores: explicitScores,
  });

  const humanScores = scoreRepoEvidence({
    readmeSignals: emptySignals,
    structureSignals: { manifestHits: [], configHits: [], workflowHints: [] },
    prSummary: {
      sampleSize: 40,
      explicitAttributedPrs: 0,
      loginAttributedPrs: 0,
      botAuthoredPrs: 0,
    },
    commitSummary: {
      sampleSize: 80,
      explicitAttributedCommits: 0,
      coauthoredAgentCommits: 0,
      mentionedAgentCommits: 0,
    },
  });

  const humanClassification = classifyRepoEvidence({
    readmeSignals: emptySignals,
    structureSignals: { manifestHits: [], configHits: [], workflowHints: [] },
    prSummary: {
      sampleSize: 40,
      explicitAttributedPrs: 0,
      loginAttributedPrs: 0,
      botAuthoredPrs: 0,
    },
    commitSummary: {
      sampleSize: 80,
      explicitAttributedCommits: 0,
      coauthoredAgentCommits: 0,
      mentionedAgentCommits: 0,
    },
    scores: humanScores,
  });

  assert.equal(explicitClassification.label, 'AI-explicit');
  assert.equal(humanClassification.label, 'human-led');
});

test('renderHtml includes repo labels and layer headers', () => {
  const html = renderHtml({
    generatedAt: '2026-03-20T00:00:00Z',
    summary: {
      cohortSize: 1,
      limitPrs: 40,
      limitCommits: 80,
      sampledPrs: 10,
      sampledCommits: 20,
      explicitRepoClaims: 1,
      manifestHeavyRepos: 1,
      reposWithLiveAttribution: 1,
      labelCounts: [{ label: 'AI-explicit', count: 1 }],
    },
    repos: [
      {
        repo: 'example/repo',
        seedLabel: 'explicit-ai-project',
        whyIncluded: 'Used as a fixture.',
        metadata: {
          htmlUrl: 'https://github.com/example/repo',
          stars: 10,
          pushedAt: '2026-03-20T00:00:00Z',
        },
        readme: {
          repoWideClaims: [{ label: 'repo-wide generated claim', snippet: 'This project was entirely generated by Claude Code.' }],
          explicitClaims: [],
          supervisionClaims: [],
        },
        structure: {
          manifestHits: [{ path: 'CLAUDE.md' }],
          configHits: [],
          workflowHints: [],
        },
        pulls: {
          sampleSize: 10,
          explicitAttributedPrs: 2,
          loginAttributedPrs: 2,
          botAuthoredPrs: 0,
          evidenceRows: [],
        },
        commits: {
          sampleSize: 20,
          explicitAttributedCommits: 3,
          coauthoredAgentCommits: 1,
          mentionedAgentCommits: 4,
          evidenceRows: [],
        },
        scores: {
          total: 60,
          readme: 30,
          manifests: 10,
          pullRequests: 12,
          commits: 8,
        },
        classification: {
          label: 'AI-explicit',
          confidence: 'high',
        },
        rationale: ['README makes a repo-wide AI-generation claim.'],
      },
    ],
  });

  assert.match(html, /Repo Authorship Signal Explorer/);
  assert.match(html, /Repo Comparison/);
  assert.match(html, /example\/repo/);
  assert.match(html, /AI-explicit/);
  assert.match(html, /Layer scores/);
});
