#!/usr/bin/env node

const https = require('https');
const fs = require('fs');
const path = require('path');

const DEFAULT_PR_LIMIT = 40;
const DEFAULT_COMMIT_LIMIT = 80;
const DEFAULT_OUT_JSON = 'output/repo-authorship-signal-explorer.json';
const DEFAULT_OUT_HTML = 'output/repo-authorship-signal-explorer.html';
const MAX_SAMPLE_ROWS = 6;

const DEFAULT_COHORT = [
  {
    repo: 'ConechoAI/Nano-Banana-MCP',
    seedLabel: 'explicit-ai-project',
    whyIncluded: 'README says the project was entirely generated by Claude Code.',
  },
  {
    repo: 'math-inc/strongpnt',
    seedLabel: 'explicit-ai-plus-human-supervision',
    whyIncluded: 'README says the repository contains AI-generated formalization with targeted human scaffolding and review.',
  },
  {
    repo: 'Aider-AI/aider',
    seedLabel: 'tool-building-itself',
    whyIncluded: 'README contains self-referential “written by Aider itself” language and this repo is a visible coding-agent product.',
  },
  {
    repo: 'OpenHands/OpenHands',
    seedLabel: 'manifest-heavy-agent-repo',
    whyIncluded: 'Root repo includes AGENTS.md and presents itself as AI-driven development infrastructure.',
  },
  {
    repo: 'numpy/numpy',
    seedLabel: 'human-led-control',
    whyIncluded: 'Large established OSS repo used here as a likely human-led control case.',
  },
];

const AGENT_KEYWORDS = [
  { label: 'claude', regex: /\bclaude(\s+code)?\b/i },
  { label: 'codex', regex: /\bcodex\b/i },
  { label: 'copilot', regex: /\bcopilot\b/i },
  { label: 'cursor', regex: /\bcursor\b/i },
  { label: 'openhands', regex: /\bopenhands\b/i },
  { label: 'aider', regex: /\baider\b/i },
  { label: 'devin', regex: /\bdevin\b/i },
  { label: 'swe-agent', regex: /\bswe[- ]agent\b/i },
  { label: 'gauss', regex: /\bgauss\b/i },
  { label: 'mcp', regex: /\bmcp\b/i },
];

const REPO_WIDE_CLAIM_PATTERNS = [
  {
    label: 'repo-wide generated claim',
    regex: /\b(entire|entirely|mostly)\s+(project|repo(?:sitory)?|application|codebase)\s+(was|is)\s+(generated|built|created|written)\s+(with|by)\b/i,
  },
  {
    label: 'repo-wide generated claim',
    regex: /\b(project|repo(?:sitory)?|application|codebase)\s+(was|is)\s+(entirely|mostly)\s+(generated|built|created|written)\s+(with|by)\b/i,
  },
  {
    label: 'repo contains AI-generated work',
    regex: /\bthis\s+repo(?:sitory)?\s+(contains|is)\s+an?\s+(ai|llm)[- ]generated\b/i,
  },
];

const EXPLICIT_ATTRIBUTION_PATTERNS = [
  {
    label: 'generated with tool',
    regex: /\bgenerated with\b[\s\S]{0,50}\b(?:claude(?:\s+code)?|codex|copilot|cursor|openhands|aider|devin|gauss|swe[- ]agent)\b/i,
  },
  {
    label: 'built with tool',
    regex: /\b(generated|built|created|written|produced)\s+(with|by)\b[\s\S]{0,50}\b(?:claude(?:\s+code)?|codex|copilot|cursor|openhands|aider|devin|gauss|swe[- ]agent)\b/i,
  },
  {
    label: 'written by tool itself',
    regex: /\bwritten by\s+(?:claude(?:\s+code)?|codex|copilot|cursor|openhands|aider|devin|gauss)\s+itself\b/i,
  },
  {
    label: 'assistance from tool',
    regex: /\b(assisted by|assistance from|with help from|help from|created with assistance from)\b[\s\S]{0,50}\b(?:claude(?:\s+code)?|codex|copilot|cursor|openhands|aider|devin|gauss|swe[- ]agent)\b/i,
  },
  {
    label: 'co-authored by tool',
    regex: /co-authored-by:[^\n]{0,100}\b(?:claude(?:\s+code)?|codex|copilot|cursor|openhands|aider|devin|gauss|swe[- ]agent)\b/i,
  },
];

const SUPERVISION_PATTERNS = [
  {
    label: 'human supervision',
    regex: /\bhuman supervision\b/i,
  },
  {
    label: 'human guidance',
    regex: /\bhuman guidance\b/i,
  },
  {
    label: 'human scaffolding',
    regex: /\bhuman scaffolding\b/i,
  },
  {
    label: 'human review',
    regex: /\b(reviewed by humans?|human review|review of key lemmas|targeted human scaffolding and review)\b/i,
  },
];

const ROOT_MANIFEST_FILES = [
  'CLAUDE.md',
  'AGENTS.md',
  'AGENT.md',
  'agents.md',
  '.cursorrules',
  '.windsurfrules',
  '.clinerules',
  '.aider.conf.yml',
  'aider.conf.yml',
];

const GITHUB_CONFIG_FILES = [
  '.github/copilot-instructions.md',
];

const WORKFLOW_KEYWORDS = ['claude', 'codex', 'copilot', 'cursor', 'openhands', 'aider', 'mcp'];

function usage() {
  return [
    'Usage: node scripts/explore_repo_authorship_signals.js [options]',
    '',
    'Options:',
    '  --repos <a,b,c>          Comma-separated owner/repo list',
    `  --limit-prs <n>         Recent PR sample size (default: ${DEFAULT_PR_LIMIT})`,
    `  --limit-commits <n>     Recent commit sample size (default: ${DEFAULT_COMMIT_LIMIT})`,
    `  --out-json <path>       JSON output path (default: ${DEFAULT_OUT_JSON})`,
    `  --out-html <path>       HTML output path (default: ${DEFAULT_OUT_HTML})`,
  ].join('\n');
}

function parseArgs(argv) {
  const args = argv.slice(2);
  const parsed = {
    help: false,
    repos: DEFAULT_COHORT.map(item => item.repo),
    limitPrs: DEFAULT_PR_LIMIT,
    limitCommits: DEFAULT_COMMIT_LIMIT,
    outJson: DEFAULT_OUT_JSON,
    outHtml: DEFAULT_OUT_HTML,
  };

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];

    if (arg === '--help' || arg === '-h') {
      parsed.help = true;
      continue;
    }

    if (arg === '--repos') {
      parsed.repos = cleanText(args[index + 1]).split(',').map(item => cleanText(item)).filter(Boolean);
      index += 1;
      continue;
    }

    if (arg === '--limit-prs') {
      parsed.limitPrs = parseInt(args[index + 1], 10);
      index += 1;
      continue;
    }

    if (arg === '--limit-commits') {
      parsed.limitCommits = parseInt(args[index + 1], 10);
      index += 1;
      continue;
    }

    if (arg === '--out-json') {
      parsed.outJson = args[index + 1];
      index += 1;
      continue;
    }

    if (arg === '--out-html') {
      parsed.outHtml = args[index + 1];
      index += 1;
      continue;
    }

    throw new Error(usage());
  }

  return parsed;
}

function cleanText(value) {
  if (value === null || value === undefined) {
    return '';
  }

  return String(value).trim();
}

function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value));
}

function encodePathSegment(pathValue) {
  return cleanText(pathValue).split('/').map(segment => encodeURIComponent(segment)).join('/');
}

function uniqueStrings(values) {
  return Array.from(new Set(values.filter(Boolean)));
}

function uniqueBy(items, getKey) {
  const seen = new Set();
  const unique = [];

  for (const item of items) {
    const key = getKey(item);
    if (seen.has(key)) {
      continue;
    }
    seen.add(key);
    unique.push(item);
  }

  return unique;
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function formatCount(value) {
  return new Intl.NumberFormat('en-US').format(value);
}

function formatDate(value) {
  return value ? cleanText(value).slice(0, 10) : '—';
}

function formatPct(count, total) {
  if (!total) {
    return '0%';
  }

  return `${Math.round((count / total) * 100)}%`;
}

function formatScore(value, max) {
  return `${Math.round(value)}/${max}`;
}

function scoreWidth(value, max) {
  return Math.max(6, Math.round((value / max) * 100));
}

function requestJson(apiPath, token) {
  return new Promise((resolve, reject) => {
    const options = {
      hostname: 'api.github.com',
      path: apiPath,
      headers: {
        'User-Agent': 'gh-pr-map-repo-authorship-signals',
        'Accept': 'application/vnd.github+json',
        ...(token ? { Authorization: `Bearer ${token}` } : {}),
      },
    };

    https.get(options, response => {
      let data = '';
      response.on('data', chunk => {
        data += chunk;
      });
      response.on('end', () => {
        let parsed;

        try {
          parsed = JSON.parse(data);
        } catch {
          const error = new Error(`Failed to parse JSON from ${apiPath}: ${data.slice(0, 160)}`);
          error.statusCode = response.statusCode || 500;
          reject(error);
          return;
        }

        if ((response.statusCode || 0) >= 400) {
          const error = new Error(`GitHub API ${response.statusCode}: ${parsed.message || 'Unknown error'}`);
          error.statusCode = response.statusCode || 500;
          reject(error);
          return;
        }

        resolve(parsed);
      });
    }).on('error', reject);
  });
}

async function ghGet(apiPath, token) {
  return requestJson(apiPath, token);
}

async function ghGetOptional(apiPath, token) {
  try {
    return await ghGet(apiPath, token);
  } catch (error) {
    if (error && error.statusCode === 404) {
      return null;
    }
    throw error;
  }
}

function fetchUrlText(url) {
  return new Promise((resolve, reject) => {
    const parsedUrl = new URL(url);
    const options = {
      hostname: parsedUrl.hostname,
      path: `${parsedUrl.pathname}${parsedUrl.search}`,
      headers: {
        'User-Agent': 'gh-pr-map-repo-authorship-signals',
      },
    };

    https.get(options, response => {
      let data = '';
      response.on('data', chunk => {
        data += chunk;
      });
      response.on('end', () => {
        if ((response.statusCode || 0) >= 400) {
          reject(new Error(`HTTP ${response.statusCode} while fetching ${url}`));
          return;
        }

        resolve(data);
      });
    }).on('error', reject);
  });
}

async function decodeContentFile(file) {
  if (!file) {
    return '';
  }

  if (file.content) {
    return Buffer.from(file.content, file.encoding || 'base64').toString('utf8');
  }

  if (file.download_url) {
    return fetchUrlText(file.download_url);
  }

  return '';
}

function excerptAround(text, regex) {
  const source = cleanText(text);
  if (!source) {
    return '';
  }

  const match = regex.exec(source);
  regex.lastIndex = 0;
  if (!match) {
    return '';
  }

  const start = Math.max(0, match.index - 60);
  const end = Math.min(source.length, match.index + match[0].length + 100);
  return source.slice(start, end).replace(/\s+/g, ' ').trim();
}

function collectPatternMatches(text, patterns) {
  const source = cleanText(text);
  if (!source) {
    return [];
  }

  const lines = source
    .split(/\r?\n/)
    .map(line => line.trim())
    .filter(Boolean);

  const matches = [];

  for (const line of lines) {
    for (const pattern of patterns) {
      if (pattern.regex.test(line)) {
        matches.push({
          label: pattern.label,
          snippet: line.slice(0, 240),
        });
      }
    }
  }

  if (!matches.length) {
    for (const pattern of patterns) {
      const snippet = excerptAround(source, pattern.regex);
      if (snippet) {
        matches.push({
          label: pattern.label,
          snippet,
        });
      }
    }
  }

  return uniqueBy(matches, match => `${match.label}:${match.snippet}`);
}

function extractAgentLabels(text) {
  const source = cleanText(text);
  if (!source) {
    return [];
  }

  return AGENT_KEYWORDS
    .filter(keyword => keyword.regex.test(source))
    .map(keyword => keyword.label);
}

function isGenericDisclosureSnippet(snippet) {
  const source = cleanText(snippet).toLowerCase();
  if (!source) {
    return false;
  }

  return (
    source.includes('tool(s) used') ||
    source.includes('how they were used') ||
    source.includes('specify what code or text is ai generated') ||
    source.includes('please describe how you used') ||
    source.includes('please specify how you used')
  );
}

function analyzeTextEvidence(text) {
  const source = cleanText(text);

  return {
    repoWideClaims: collectPatternMatches(source, REPO_WIDE_CLAIM_PATTERNS),
    explicitClaims: collectPatternMatches(source, EXPLICIT_ATTRIBUTION_PATTERNS),
    supervisionClaims: collectPatternMatches(source, SUPERVISION_PATTERNS),
    agentLabels: extractAgentLabels(source),
  };
}

function isBotIdentity(login, type, fallbackName) {
  const normalizedLogin = cleanText(login).toLowerCase();
  const normalizedType = cleanText(type).toLowerCase();
  const normalizedName = cleanText(fallbackName).toLowerCase();

  return normalizedType === 'bot' || /\[bot\]$/.test(normalizedLogin) || /\[bot\]$/.test(normalizedName);
}

function countByLabel(items, getLabels) {
  const counts = new Map();

  for (const item of items) {
    const labels = getLabels(item);
    for (const label of labels) {
      if (!label) {
        continue;
      }
      if (!counts.has(label)) {
        counts.set(label, { label, count: 0 });
      }
      counts.get(label).count += 1;
    }
  }

  return Array.from(counts.values()).sort((left, right) => {
    if (right.count !== left.count) {
      return right.count - left.count;
    }
    return left.label.localeCompare(right.label);
  });
}

async function fetchRepoMetadata(repo, token) {
  const metadata = await ghGet(`/repos/${repo}`, token);
  return {
    repo,
    htmlUrl: cleanText(metadata.html_url) || `https://github.com/${repo}`,
    description: cleanText(metadata.description),
    defaultBranch: cleanText(metadata.default_branch) || 'main',
    stars: metadata.stargazers_count || 0,
    forks: metadata.forks_count || 0,
    openIssues: metadata.open_issues_count || 0,
    language: cleanText(metadata.language),
    license: metadata.license
      ? (cleanText(metadata.license.spdx_id) || cleanText(metadata.license.name) || 'Present')
      : 'No license detected',
    pushedAt: cleanText(metadata.pushed_at),
    createdAt: cleanText(metadata.created_at),
  };
}

async function fetchReadme(repo, token) {
  const readme = await ghGetOptional(`/repos/${repo}/readme`, token);
  if (!readme) {
    return {
      path: '',
      text: '',
      htmlUrl: '',
    };
  }

  return {
    path: cleanText(readme.path),
    text: await decodeContentFile(readme),
    htmlUrl: cleanText(readme.html_url),
  };
}

async function fetchDirectory(repo, directoryPath, token) {
  const apiPath = directoryPath
    ? `/repos/${repo}/contents/${encodePathSegment(directoryPath)}`
    : `/repos/${repo}/contents`;
  const entries = await ghGetOptional(apiPath, token);
  return Array.isArray(entries) ? entries : [];
}

async function fetchRepoStructure(repo, token) {
  const rootEntries = await fetchDirectory(repo, '', token);
  const rootNames = new Set(rootEntries.map(entry => entry.name));

  const githubEntries = rootNames.has('.github')
    ? await fetchDirectory(repo, '.github', token)
    : [];
  const githubNames = new Set(githubEntries.map(entry => entry.name));

  const workflowEntries = githubNames.has('workflows')
    ? await fetchDirectory(repo, '.github/workflows', token)
    : [];

  const cursorEntries = rootNames.has('.cursor')
    ? await fetchDirectory(repo, '.cursor', token)
    : [];
  const cursorNames = new Set(cursorEntries.map(entry => entry.name));

  const instructionEntries = githubNames.has('instructions')
    ? await fetchDirectory(repo, '.github/instructions', token)
    : [];

  const manifestHits = [];
  const configHits = [];
  const workflowHints = [];

  for (const fileName of ROOT_MANIFEST_FILES) {
    if (rootNames.has(fileName)) {
      manifestHits.push({ path: fileName, kind: 'root-manifest' });
    }
  }

  for (const filePath of GITHUB_CONFIG_FILES) {
    const fileName = filePath.replace('.github/', '');
    if (githubNames.has(fileName)) {
      configHits.push({ path: filePath, kind: 'github-config' });
    }
  }

  if (cursorNames.has('rules')) {
    configHits.push({ path: '.cursor/rules', kind: 'cursor-rules' });
  }

  if (instructionEntries.length) {
    configHits.push({ path: '.github/instructions/', kind: 'github-instructions' });
  }

  for (const entry of workflowEntries) {
    if (entry.type !== 'file') {
      continue;
    }

    const normalizedName = cleanText(entry.name).toLowerCase();
    const matchedKeyword = WORKFLOW_KEYWORDS.find(keyword => normalizedName.includes(keyword));

    if (matchedKeyword) {
      workflowHints.push({
        path: cleanText(entry.path),
        keyword: matchedKeyword,
      });
    }
  }

  return {
    manifestHits: uniqueBy(manifestHits, item => item.path),
    configHits: uniqueBy(configHits, item => item.path),
    workflowHints: uniqueBy(workflowHints, item => item.path),
  };
}

async function fetchPullRequests(repo, limitPrs, token) {
  const pulls = await ghGet(
    `/repos/${repo}/pulls?state=all&sort=updated&direction=desc&per_page=${limitPrs}`,
    token
  );
  if (!Array.isArray(pulls)) {
    throw new Error(`Unexpected PR response for ${repo}`);
  }
  return pulls;
}

async function fetchCommits(repo, limitCommits, token) {
  const commits = await ghGet(
    `/repos/${repo}/commits?per_page=${limitCommits}`,
    token
  );
  if (!Array.isArray(commits)) {
    throw new Error(`Unexpected commit response for ${repo}`);
  }
  return commits;
}

function summarizePullRequests(pulls) {
  const evidenceRows = [];
  const agentLabelRows = [];

  let botAuthoredPrs = 0;
  let loginAttributedPrs = 0;
  let titleAttributedPrs = 0;
  let bodyAttributedPrs = 0;
  let explicitAttributedPrs = 0;
  let agentSignalPrs = 0;

  for (const pr of pulls) {
    const login = cleanText(pr.user && pr.user.login);
    const userType = cleanText(pr.user && pr.user.type);
    const title = cleanText(pr.title);
    const body = cleanText(pr.body);
    const botAuthor = isBotIdentity(login, userType, '');

    const titleEvidence = analyzeTextEvidence(title);
    const bodyEvidence = analyzeTextEvidence(body);
    const loginLabels = extractAgentLabels(login);
    const titleLabels = extractAgentLabels(title);
    const bodyLabels = extractAgentLabels(body);
    const agentLabels = uniqueStrings([...loginLabels, ...titleLabels, ...bodyLabels]);

    const titleSnippet = titleEvidence.repoWideClaims[0] || titleEvidence.explicitClaims[0] || null;
    const bodySnippet = bodyEvidence.repoWideClaims[0] || bodyEvidence.explicitClaims[0] || null;
    const titleAttributed = Boolean(titleSnippet) && !isGenericDisclosureSnippet(titleSnippet.snippet);
    const bodyAttributed = Boolean(bodySnippet) && !isGenericDisclosureSnippet(bodySnippet.snippet);
    const explicitAttributed = titleAttributed || bodyAttributed;
    const loginAttributed = loginLabels.length > 0;

    if (botAuthor) {
      botAuthoredPrs += 1;
    }
    if (loginAttributed) {
      loginAttributedPrs += 1;
    }
    if (titleAttributed) {
      titleAttributedPrs += 1;
    }
    if (bodyAttributed) {
      bodyAttributedPrs += 1;
    }
    if (explicitAttributed) {
      explicitAttributedPrs += 1;
    }
    if (agentLabels.length > 0) {
      agentSignalPrs += 1;
      agentLabelRows.push({ labels: agentLabels });
    }

    if (evidenceRows.length >= MAX_SAMPLE_ROWS) {
      continue;
    }

    if (!explicitAttributed && !loginAttributed && !botAuthor) {
      continue;
    }

    const snippet = bodyAttributed
      ? bodySnippet
      : (titleAttributed ? titleSnippet : null);

    const sources = [];
    if (bodyAttributed) {
      sources.push('body');
    }
    if (titleAttributed) {
      sources.push('title');
    }
    if (loginAttributed) {
      sources.push('login');
    }
    if (botAuthor) {
      sources.push('bot');
    }

    evidenceRows.push({
      number: pr.number,
      title,
      htmlUrl: cleanText(pr.html_url),
      createdAt: cleanText(pr.created_at),
      authorLogin: login || 'unknown',
      sources,
      labels: agentLabels,
      snippet: snippet ? snippet.snippet : '',
    });
  }

  return {
    sampleSize: pulls.length,
    botAuthoredPrs,
    loginAttributedPrs,
    titleAttributedPrs,
    bodyAttributedPrs,
    explicitAttributedPrs,
    agentSignalPrs,
    topAgentLabels: countByLabel(agentLabelRows, row => row.labels),
    evidenceRows,
  };
}

function summarizeCommits(commits) {
  const evidenceRows = [];
  const agentLabelRows = [];

  let botAuthoredCommits = 0;
  let explicitAttributedCommits = 0;
  let coauthoredAgentCommits = 0;
  let mentionedAgentCommits = 0;

  for (const commit of commits) {
    const message = cleanText(commit.commit && commit.commit.message);
    const login = cleanText(commit.author && commit.author.login);
    const authorType = cleanText(commit.author && commit.author.type);
    const authorName = cleanText(commit.commit && commit.commit.author && commit.commit.author.name);
    const htmlUrl = cleanText(commit.html_url);
    const committedAt = cleanText(commit.commit && commit.commit.author && commit.commit.author.date);

    const botAuthor = isBotIdentity(login, authorType, authorName);
    const evidence = analyzeTextEvidence(message);
    const coauthoredAgent = /co-authored-by:[\s\S]{0,100}\b(?:claude(?:\s+code)?|codex|copilot|cursor|openhands|aider|devin|gauss|swe[- ]agent)\b/i.test(message);
    const labels = uniqueStrings([...evidence.agentLabels, ...extractAgentLabels(login), ...extractAgentLabels(authorName)]);
    const evidenceSnippet = evidence.repoWideClaims[0] || evidence.explicitClaims[0] || null;
    const explicitAttributed = (
      (Boolean(evidenceSnippet) && !isGenericDisclosureSnippet(evidenceSnippet.snippet)) ||
      coauthoredAgent
    );

    if (botAuthor) {
      botAuthoredCommits += 1;
    }
    if (explicitAttributed) {
      explicitAttributedCommits += 1;
    }
    if (coauthoredAgent) {
      coauthoredAgentCommits += 1;
    }
    if (labels.length > 0) {
      mentionedAgentCommits += 1;
      agentLabelRows.push({ labels });
    }

    if (evidenceRows.length >= MAX_SAMPLE_ROWS) {
      continue;
    }

    if (!explicitAttributed && !labels.length && !botAuthor) {
      continue;
    }

    const snippet = explicitAttributed && evidenceSnippet && !isGenericDisclosureSnippet(evidenceSnippet.snippet)
      ? evidenceSnippet
      : null;

    evidenceRows.push({
      sha: cleanText(commit.sha).slice(0, 7),
      htmlUrl,
      committedAt,
      authorLogin: login || authorName || 'unknown',
      labels,
      sources: uniqueStrings([
        explicitAttributed ? 'message' : '',
        coauthoredAgent ? 'co-author' : '',
        botAuthor ? 'bot' : '',
      ]),
      snippet: snippet ? snippet.snippet : message.split('\n')[0].slice(0, 200),
    });
  }

  return {
    sampleSize: commits.length,
    botAuthoredCommits,
    explicitAttributedCommits,
    coauthoredAgentCommits,
    mentionedAgentCommits,
    topAgentLabels: countByLabel(agentLabelRows, row => row.labels),
    evidenceRows,
  };
}

function scoreRepoEvidence({ readmeSignals, structureSignals, prSummary, commitSummary }) {
  let readmeScore = 0;
  if (readmeSignals.repoWideClaims.length) {
    readmeScore += 24;
  }
  readmeScore += Math.min(12, readmeSignals.explicitClaims.length * 6);
  readmeScore += Math.min(5, readmeSignals.supervisionClaims.length * 2);

  let manifestScore = 0;
  manifestScore += structureSignals.manifestHits.length * 6;
  manifestScore += structureSignals.configHits.length * 4;
  manifestScore += structureSignals.workflowHints.length * 2;

  let pullRequestScore = 0;
  if (prSummary.sampleSize) {
    pullRequestScore += (prSummary.explicitAttributedPrs / prSummary.sampleSize) * 18;
    pullRequestScore += (prSummary.loginAttributedPrs / prSummary.sampleSize) * 8;
    pullRequestScore += (prSummary.botAuthoredPrs / prSummary.sampleSize) * 4;
    if (prSummary.explicitAttributedPrs >= 3) {
      pullRequestScore += 3;
    }
  }

  let commitScore = 0;
  if (commitSummary.sampleSize) {
    commitScore += (commitSummary.explicitAttributedCommits / commitSummary.sampleSize) * 14;
    commitScore += (commitSummary.coauthoredAgentCommits / commitSummary.sampleSize) * 8;
    commitScore += (commitSummary.mentionedAgentCommits / commitSummary.sampleSize) * 4;
  }

  const scores = {
    readme: clamp(readmeScore, 0, 35),
    manifests: clamp(manifestScore, 0, 22),
    pullRequests: clamp(pullRequestScore, 0, 24),
    commits: clamp(commitScore, 0, 19),
  };
  scores.total = scores.readme + scores.manifests + scores.pullRequests + scores.commits;

  return scores;
}

function buildRationale({ readmeSignals, structureSignals, prSummary, commitSummary }) {
  const points = [];

  if (readmeSignals.repoWideClaims.length) {
    points.push('README makes a repo-wide AI-generation claim.');
  } else if (readmeSignals.explicitClaims.length) {
    points.push('README or description uses explicit AI authorship wording.');
  }

  if (readmeSignals.supervisionClaims.length) {
    points.push('Public docs also mention human supervision or review.');
  }

  if (structureSignals.manifestHits.length) {
    points.push(`Manifest files found: ${structureSignals.manifestHits.map(item => item.path).join(', ')}.`);
  } else if (structureSignals.configHits.length) {
    points.push(`Agent config hints found: ${structureSignals.configHits.map(item => item.path).join(', ')}.`);
  }

  if (prSummary.explicitAttributedPrs) {
    points.push(`${formatCount(prSummary.explicitAttributedPrs)} of ${formatCount(prSummary.sampleSize)} sampled PRs contain explicit attribution language.`);
  } else if (prSummary.loginAttributedPrs) {
    points.push(`${formatCount(prSummary.loginAttributedPrs)} sampled PRs use agent-like author logins.`);
  }

  if (commitSummary.explicitAttributedCommits) {
    points.push(`${formatCount(commitSummary.explicitAttributedCommits)} of ${formatCount(commitSummary.sampleSize)} sampled commits contain explicit attribution signals.`);
  } else if (commitSummary.mentionedAgentCommits) {
    points.push(`${formatCount(commitSummary.mentionedAgentCommits)} sampled commits mention agent tools by name.`);
  }

  return points.slice(0, 4);
}

function classifyRepoEvidence({ readmeSignals, structureSignals, prSummary, commitSummary, scores }) {
  const combinedSampleSize = prSummary.sampleSize + commitSummary.sampleSize;
  const hasRepoWideClaim = readmeSignals.repoWideClaims.length > 0;
  const hasAnyExplicitClaim = hasRepoWideClaim || readmeSignals.explicitClaims.length > 0;
  const hasManifestHints = structureSignals.manifestHits.length > 0 || structureSignals.configHits.length > 0;
  const hasLiveAttribution = prSummary.explicitAttributedPrs > 0 || commitSummary.explicitAttributedCommits > 0;

  if (hasRepoWideClaim) {
    return {
      label: 'AI-explicit',
      confidence: 'high',
    };
  }

  if (
    scores.total >= 20 &&
    readmeSignals.explicitClaims.length > 0 &&
    (commitSummary.explicitAttributedCommits >= 10 || prSummary.explicitAttributedPrs >= 3)
  ) {
    return {
      label: 'AI-first',
      confidence: scores.total >= 32 ? 'high' : 'medium',
    };
  }

  if (
    scores.total >= 34 &&
    (scores.pullRequests >= 6 || scores.commits >= 5 || scores.manifests >= 10 || hasAnyExplicitClaim)
  ) {
    return {
      label: 'AI-first',
      confidence: scores.total >= 46 ? 'high' : 'medium',
    };
  }

  if (
    !hasAnyExplicitClaim &&
    !hasManifestHints &&
    scores.total <= 6 &&
    combinedSampleSize >= 30
  ) {
    return {
      label: 'human-led',
      confidence: 'medium',
    };
  }

  if (scores.total >= 12 || hasAnyExplicitClaim || hasManifestHints || hasLiveAttribution) {
    return {
      label: 'mixed',
      confidence: scores.total >= 24 ? 'medium' : 'low',
    };
  }

  if (combinedSampleSize >= 30) {
    return {
      label: 'human-led',
      confidence: scores.total <= 4 ? 'high' : 'medium',
    };
  }

  return {
    label: 'unknown',
    confidence: 'low',
  };
}

async function buildRepoReport(cohortItem, options) {
  const { token, limitPrs, limitCommits } = options;
  const repo = cohortItem.repo;

  console.log(`Sampling ${repo}...`);

  const metadata = await fetchRepoMetadata(repo, token);
  const readme = await fetchReadme(repo, token);
  const structureSignals = await fetchRepoStructure(repo, token);
  const pulls = await fetchPullRequests(repo, limitPrs, token);
  const commits = await fetchCommits(repo, limitCommits, token);

  const readmeBundle = [
    metadata.description ? `Description: ${metadata.description}` : '',
    readme.text,
  ].filter(Boolean).join('\n\n');

  const readmeSignals = analyzeTextEvidence(readmeBundle);
  const prSummary = summarizePullRequests(pulls);
  const commitSummary = summarizeCommits(commits);
  const scores = scoreRepoEvidence({
    readmeSignals,
    structureSignals,
    prSummary,
    commitSummary,
  });
  const classification = classifyRepoEvidence({
    readmeSignals,
    structureSignals,
    prSummary,
    commitSummary,
    scores,
  });

  return {
    repo,
    seedLabel: cleanText(cohortItem.seedLabel),
    whyIncluded: cleanText(cohortItem.whyIncluded),
    metadata,
    readme: {
      path: readme.path,
      htmlUrl: readme.htmlUrl,
      repoWideClaims: readmeSignals.repoWideClaims,
      explicitClaims: readmeSignals.explicitClaims,
      supervisionClaims: readmeSignals.supervisionClaims,
      agentLabels: readmeSignals.agentLabels,
    },
    structure: structureSignals,
    pulls: prSummary,
    commits: commitSummary,
    scores,
    classification,
    rationale: buildRationale({
      readmeSignals,
      structureSignals,
      prSummary,
      commitSummary,
    }),
  };
}

function countLabels(items, getLabel) {
  const counts = new Map();

  for (const item of items) {
    const label = getLabel(item);
    if (!counts.has(label)) {
      counts.set(label, { label, count: 0 });
    }
    counts.get(label).count += 1;
  }

  return Array.from(counts.values()).sort((left, right) => {
    if (right.count !== left.count) {
      return right.count - left.count;
    }
    return left.label.localeCompare(right.label);
  });
}

function buildSummary(repos, options) {
  return {
    cohortSize: repos.length,
    limitPrs: options.limitPrs,
    limitCommits: options.limitCommits,
    sampledPrs: repos.reduce((sum, repo) => sum + repo.pulls.sampleSize, 0),
    sampledCommits: repos.reduce((sum, repo) => sum + repo.commits.sampleSize, 0),
    explicitRepoClaims: repos.filter(repo => repo.readme.repoWideClaims.length > 0).length,
    manifestHeavyRepos: repos.filter(repo => repo.structure.manifestHits.length > 0 || repo.structure.configHits.length > 0).length,
    reposWithLiveAttribution: repos.filter(repo => repo.pulls.explicitAttributedPrs > 0 || repo.commits.explicitAttributedCommits > 0).length,
    labelCounts: countLabels(repos, repo => repo.classification.label),
  };
}

function labelClass(label) {
  switch (label) {
    case 'AI-explicit':
      return 'label-explicit';
    case 'AI-first':
      return 'label-first';
    case 'mixed':
      return 'label-mixed';
    case 'human-led':
      return 'label-human';
    default:
      return 'label-unknown';
  }
}

function renderTable(headers, rows) {
  return `<table>
  <thead>
    <tr>${headers.map(header => `<th>${escapeHtml(header)}</th>`).join('')}</tr>
  </thead>
  <tbody>
${rows.map(row => `    <tr>${row.map(cell => `<td>${cell}</td>`).join('')}</tr>`).join('\n')}
  </tbody>
</table>`;
}

function renderList(items, emptyText, renderItem = item => escapeHtml(item)) {
  if (!items.length) {
    return `<p class="empty">${escapeHtml(emptyText)}</p>`;
  }

  return `<ul class="evidence-list">
${items.map(item => `  <li>${renderItem(item)}</li>`).join('\n')}
</ul>`;
}

function renderScoreBars(repo) {
  const layers = [
    { label: 'README', value: repo.scores.readme, max: 35 },
    { label: 'Manifest', value: repo.scores.manifests, max: 22 },
    { label: 'PRs', value: repo.scores.pullRequests, max: 24 },
    { label: 'Commits', value: repo.scores.commits, max: 19 },
  ];

  return `<div class="score-bars">
${layers.map(layer => `  <div class="score-row">
    <div class="score-name">${escapeHtml(layer.label)}</div>
    <div class="score-track"><div class="score-fill" style="width:${scoreWidth(layer.value, layer.max)}%"></div></div>
    <div class="score-value">${escapeHtml(formatScore(layer.value, layer.max))}</div>
  </div>`).join('\n')}
</div>`;
}

function renderRepoSection(repo) {
  const repoWideClaims = [...repo.readme.repoWideClaims, ...repo.readme.explicitClaims]
    .slice(0, 5);

  return `<section class="repo-section">
    <div class="repo-heading">
      <div>
        <h2><a href="${escapeHtml(repo.metadata.htmlUrl)}" target="_blank" rel="noreferrer">${escapeHtml(repo.repo)}</a></h2>
        <p class="muted">${escapeHtml(repo.whyIncluded)}</p>
      </div>
      <div class="repo-heading-side">
        <span class="label-chip ${labelClass(repo.classification.label)}">${escapeHtml(repo.classification.label)}</span>
        <div class="confidence">${escapeHtml(repo.classification.confidence)} confidence</div>
      </div>
    </div>

    <div class="meta-grid">
      <div class="meta-card">
        <div class="meta-label">Total score</div>
        <div class="meta-value">${formatScore(repo.scores.total, 100)}</div>
      </div>
      <div class="meta-card">
        <div class="meta-label">Stars</div>
        <div class="meta-value">${formatCount(repo.metadata.stars)}</div>
      </div>
      <div class="meta-card">
        <div class="meta-label">Sampled PRs</div>
        <div class="meta-value">${formatCount(repo.pulls.sampleSize)}</div>
      </div>
      <div class="meta-card">
        <div class="meta-label">Sampled commits</div>
        <div class="meta-value">${formatCount(repo.commits.sampleSize)}</div>
      </div>
      <div class="meta-card">
        <div class="meta-label">Seed role</div>
        <div class="meta-value small">${escapeHtml(repo.seedLabel)}</div>
      </div>
      <div class="meta-card">
        <div class="meta-label">Pushed</div>
        <div class="meta-value small">${escapeHtml(formatDate(repo.metadata.pushedAt))}</div>
      </div>
    </div>

    <div class="panel">
      <h3>Layer scores</h3>
      ${renderScoreBars(repo)}
      ${renderList(repo.rationale, 'No rationale points recorded.')}
    </div>

    <div class="repo-panels">
      <div class="panel">
        <h3>README and description evidence</h3>
        ${renderList(
          repoWideClaims,
          'No explicit AI authorship phrases matched in the README or description sample.',
          item => `<strong>${escapeHtml(item.label)}:</strong> ${escapeHtml(item.snippet)}`
        )}
        ${repo.readme.supervisionClaims.length
          ? `<h4>Human-supervision phrases</h4>${renderList(
              repo.readme.supervisionClaims,
              '',
              item => escapeHtml(item.snippet)
            )}`
          : ''}
      </div>

      <div class="panel">
        <h3>Manifest and workflow hints</h3>
        <h4>Manifest files</h4>
        ${renderList(
          repo.structure.manifestHits,
          'No manifest files detected in the sampled paths.',
          item => `<code>${escapeHtml(item.path)}</code>`
        )}
        <h4>Config hints</h4>
        ${renderList(
          repo.structure.configHits,
          'No agent config files detected in the sampled paths.',
          item => `<code>${escapeHtml(item.path)}</code>`
        )}
        <h4>Workflow hints</h4>
        ${renderList(
          repo.structure.workflowHints,
          'No AI-specific workflow filenames detected.',
          item => `<code>${escapeHtml(item.path)}</code> <span class="muted">(${escapeHtml(item.keyword)})</span>`
        )}
      </div>
    </div>

    <div class="repo-panels">
      <div class="panel">
        <h3>Recent PR sample</h3>
        <p class="muted">${formatCount(repo.pulls.explicitAttributedPrs)} explicit, ${formatCount(repo.pulls.loginAttributedPrs)} login-attributed, ${formatCount(repo.pulls.botAuthoredPrs)} bot-authored.</p>
        ${repo.pulls.evidenceRows.length
          ? renderTable(
              ['PR', 'Author', 'Sources', 'Labels', 'Date'],
              repo.pulls.evidenceRows.map(row => [
                `<a href="${escapeHtml(row.htmlUrl)}" target="_blank" rel="noreferrer">${escapeHtml(`#${row.number} ${row.title}`)}</a><div class="subtle">${escapeHtml(row.snippet || '—')}</div>`,
                escapeHtml(row.authorLogin),
                escapeHtml(row.sources.join(', ')),
                escapeHtml(row.labels.join(', ') || '—'),
                escapeHtml(formatDate(row.createdAt)),
              ])
            )
          : '<p class="empty">No explicit or login-attributed PRs were found in the recent sample.</p>'}
      </div>

      <div class="panel">
        <h3>Recent commit sample</h3>
        <p class="muted">${formatCount(repo.commits.explicitAttributedCommits)} explicit, ${formatCount(repo.commits.coauthoredAgentCommits)} co-authored, ${formatCount(repo.commits.mentionedAgentCommits)} with tool mentions.</p>
        ${repo.commits.evidenceRows.length
          ? renderTable(
              ['Commit', 'Author', 'Sources', 'Labels', 'Date'],
              repo.commits.evidenceRows.map(row => [
                `<a href="${escapeHtml(row.htmlUrl)}" target="_blank" rel="noreferrer">${escapeHtml(row.sha)}</a><div class="subtle">${escapeHtml(row.snippet || '—')}</div>`,
                escapeHtml(row.authorLogin),
                escapeHtml(row.sources.join(', ') || '—'),
                escapeHtml(row.labels.join(', ') || '—'),
                escapeHtml(formatDate(row.committedAt)),
              ])
            )
          : '<p class="empty">No explicit or agent-mentioning commits were found in the recent sample.</p>'}
      </div>
    </div>
  </section>`;
}

function renderHtml(report) {
  const labelSummary = report.summary.labelCounts
    .map(item => `${item.label}: ${formatCount(item.count)}`)
    .join(' | ');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Repo Authorship Signal Explorer</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    :root {
      --bg: #f1efe7;
      --paper: #fffdf7;
      --ink: #1d2733;
      --muted: #627181;
      --border: #d8d0bf;
      --accent: #1b6b6f;
      --accent-soft: #8bc3bf;
      --explicit: #9d2f2f;
      --ai-first: #b05600;
      --mixed: #5c4d9b;
      --human: #2f6b3e;
      --unknown: #76808d;
      --shadow: 0 22px 48px rgba(29, 39, 51, 0.08);
    }

    * { box-sizing: border-box; }

    body {
      margin: 0;
      padding: 32px 20px 48px;
      background:
        radial-gradient(circle at top right, rgba(27, 107, 111, 0.12), transparent 24%),
        radial-gradient(circle at top left, rgba(181, 86, 0, 0.1), transparent 20%),
        var(--bg);
      color: var(--ink);
      font-family: "Iowan Old Style", "Palatino Linotype", "Book Antiqua", Palatino, Georgia, serif;
      line-height: 1.55;
    }

    .page {
      max-width: 1220px;
      margin: 0 auto;
    }

    .hero, .panel, .repo-section {
      background: var(--paper);
      border: 1px solid var(--border);
      border-radius: 20px;
      box-shadow: var(--shadow);
    }

    .hero {
      padding: 28px 28px 24px;
      margin-bottom: 22px;
    }

    h1, h2, h3, h4 {
      margin: 0 0 10px;
      line-height: 1.15;
    }

    h1 {
      font-size: 42px;
      letter-spacing: -0.03em;
    }

    h2 {
      font-size: 28px;
    }

    h3 {
      font-size: 21px;
    }

    h4 {
      font-size: 16px;
      color: var(--muted);
      margin-top: 18px;
    }

    p {
      margin: 0 0 12px;
    }

    a {
      color: var(--accent);
    }

    .muted, .subtle, .confidence {
      color: var(--muted);
    }

    .subtle {
      font-size: 13px;
      margin-top: 4px;
    }

    .summary-grid, .meta-grid, .repo-panels {
      display: grid;
      gap: 16px;
    }

    .summary-grid {
      grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
      margin-top: 20px;
    }

    .meta-grid {
      grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
      margin-bottom: 18px;
    }

    .repo-panels {
      grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
      margin-top: 16px;
    }

    .summary-card, .meta-card {
      border: 1px solid var(--border);
      border-radius: 16px;
      background: rgba(255, 255, 255, 0.6);
      padding: 16px 18px;
    }

    .summary-label, .meta-label {
      color: var(--muted);
      font-size: 13px;
      text-transform: uppercase;
      letter-spacing: 0.08em;
      margin-bottom: 8px;
    }

    .summary-value, .meta-value {
      font-size: 28px;
      font-weight: 700;
    }

    .meta-value.small {
      font-size: 16px;
      line-height: 1.3;
    }

    .panel {
      padding: 20px 22px;
      margin-top: 18px;
    }

    .repo-section {
      padding: 24px 24px 20px;
      margin-top: 22px;
    }

    .repo-heading {
      display: flex;
      justify-content: space-between;
      gap: 16px;
      align-items: flex-start;
      margin-bottom: 16px;
    }

    .repo-heading-side {
      text-align: right;
      min-width: 140px;
    }

    .label-chip {
      display: inline-block;
      padding: 8px 12px;
      border-radius: 999px;
      font-size: 13px;
      font-weight: 700;
      letter-spacing: 0.04em;
      text-transform: uppercase;
      color: white;
    }

    .label-explicit { background: var(--explicit); }
    .label-first { background: var(--ai-first); }
    .label-mixed { background: var(--mixed); }
    .label-human { background: var(--human); }
    .label-unknown { background: var(--unknown); }

    .score-bars {
      display: grid;
      gap: 10px;
      margin-top: 12px;
    }

    .score-row {
      display: grid;
      grid-template-columns: 78px 1fr 64px;
      gap: 12px;
      align-items: center;
    }

    .score-name, .score-value {
      font-size: 14px;
    }

    .score-track {
      width: 100%;
      height: 12px;
      border-radius: 999px;
      background: #e8e2d6;
      overflow: hidden;
    }

    .score-fill {
      height: 100%;
      background: linear-gradient(90deg, var(--accent), var(--accent-soft));
      border-radius: inherit;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      font-size: 14px;
    }

    th, td {
      border-bottom: 1px solid #eadfce;
      text-align: left;
      padding: 10px 8px;
      vertical-align: top;
    }

    th {
      color: var(--muted);
      font-size: 12px;
      text-transform: uppercase;
      letter-spacing: 0.06em;
    }

    .evidence-list {
      margin: 0;
      padding-left: 18px;
    }

    .evidence-list li {
      margin-bottom: 8px;
    }

    .empty {
      color: var(--muted);
      margin: 0;
    }

    .footnote {
      margin-top: 22px;
      color: var(--muted);
      font-size: 13px;
    }

    @media (max-width: 860px) {
      body {
        padding: 16px 12px 28px;
      }

      h1 {
        font-size: 32px;
      }

      .repo-heading {
        flex-direction: column;
      }

      .repo-heading-side {
        text-align: left;
      }

      .score-row {
        grid-template-columns: 64px 1fr 56px;
      }
    }
  </style>
</head>
<body>
  <div class="page">
    <section class="hero">
      <h1>Repo Authorship Signal Explorer</h1>
      <p>This experiment samples a small, deliberately varied cohort of public repositories and fuses several public evidence layers: README claims, manifest or config files, workflow hints, recent pull requests, and recent commits. The goal is breadth, not certainty.</p>
      <p class="muted">Labels are heuristic and should be read as evidence-weighted summaries, not proof. Recent sample limits here are ${formatCount(report.summary.limitPrs)} PRs and ${formatCount(report.summary.limitCommits)} commits per repo.</p>

      <div class="summary-grid">
        <div class="summary-card">
          <div class="summary-label">Repo cohort</div>
          <div class="summary-value">${formatCount(report.summary.cohortSize)}</div>
          <p>${escapeHtml(labelSummary || 'No labels')}</p>
        </div>
        <div class="summary-card">
          <div class="summary-label">Sampled PRs</div>
          <div class="summary-value">${formatCount(report.summary.sampledPrs)}</div>
          <p>${formatCount(report.summary.reposWithLiveAttribution)} repos showed live PR or commit attribution.</p>
        </div>
        <div class="summary-card">
          <div class="summary-label">Sampled commits</div>
          <div class="summary-value">${formatCount(report.summary.sampledCommits)}</div>
          <p>${formatCount(report.summary.explicitRepoClaims)} repos made repo-wide explicit AI claims.</p>
        </div>
        <div class="summary-card">
          <div class="summary-label">Manifest-heavy repos</div>
          <div class="summary-value">${formatCount(report.summary.manifestHeavyRepos)}</div>
          <p>Based on <code>CLAUDE.md</code>, <code>AGENTS.md</code>, tool config files, and workflow hints.</p>
        </div>
      </div>
    </section>

    <section class="panel">
      <h2>Repo Comparison</h2>
      <p class="muted">This table keeps the layers separate so one weak hint does not dominate the whole classification.</p>
      ${renderTable(
        ['Repo', 'Seed role', 'Label', 'Total score', 'README', 'Manifest', 'PRs', 'Commits', 'Recent PR sample', 'Recent commit sample'],
        report.repos.map(repo => [
          `<a href="${escapeHtml(repo.metadata.htmlUrl)}" target="_blank" rel="noreferrer">${escapeHtml(repo.repo)}</a>`,
          escapeHtml(repo.seedLabel),
          `<span class="label-chip ${labelClass(repo.classification.label)}">${escapeHtml(repo.classification.label)}</span>`,
          escapeHtml(formatScore(repo.scores.total, 100)),
          escapeHtml(formatScore(repo.scores.readme, 35)),
          escapeHtml(formatScore(repo.scores.manifests, 22)),
          escapeHtml(formatScore(repo.scores.pullRequests, 24)),
          escapeHtml(formatScore(repo.scores.commits, 19)),
          escapeHtml(`${formatCount(repo.pulls.explicitAttributedPrs)} explicit / ${formatPct(repo.pulls.explicitAttributedPrs, repo.pulls.sampleSize)}`),
          escapeHtml(`${formatCount(repo.commits.explicitAttributedCommits)} explicit / ${formatPct(repo.commits.explicitAttributedCommits, repo.commits.sampleSize)}`),
        ])
      )}
    </section>

    ${report.repos.map(renderRepoSection).join('\n')}

    <p class="footnote">Generated ${escapeHtml(report.generatedAt)}. Cohort: ${escapeHtml(report.repos.map(repo => repo.repo).join(', '))}. Public data only. Strong README claims push a repo toward <code>AI-explicit</code>; weaker hints, manifests, and live PR or commit evidence tend to land in <code>AI-first</code> or <code>mixed</code>.</p>
  </div>
</body>
</html>`;
}

async function main() {
  const parsed = parseArgs(process.argv);

  if (parsed.help) {
    console.log(usage());
    return;
  }

  const token = process.env.GITHUB_TOKEN || '';
  if (!token) {
    console.warn('Warning: GITHUB_TOKEN is not set. API rate limits may be low.');
  }

  const cohort = parsed.repos.map(repo => {
    const found = DEFAULT_COHORT.find(item => item.repo === repo);
    return found || {
      repo,
      seedLabel: 'custom',
      whyIncluded: 'Custom cohort item supplied via CLI.',
    };
  });

  const repos = [];

  for (const cohortItem of cohort) {
    repos.push(await buildRepoReport(cohortItem, {
      token,
      limitPrs: parsed.limitPrs,
      limitCommits: parsed.limitCommits,
    }));
  }

  repos.sort((left, right) => {
    if (right.scores.total !== left.scores.total) {
      return right.scores.total - left.scores.total;
    }
    return left.repo.localeCompare(right.repo);
  });

  const report = {
    generatedAt: new Date().toISOString(),
    cohortType: 'breadth-variants',
    summary: buildSummary(repos, parsed),
    repos,
  };

  fs.mkdirSync(path.dirname(parsed.outJson), { recursive: true });
  fs.writeFileSync(parsed.outJson, `${JSON.stringify(report, null, 2)}\n`);
  fs.mkdirSync(path.dirname(parsed.outHtml), { recursive: true });
  fs.writeFileSync(parsed.outHtml, renderHtml(report));

  console.log(`Saved JSON to ${parsed.outJson}`);
  console.log(`Saved HTML to ${parsed.outHtml}`);
  console.log(`${formatCount(report.summary.cohortSize)} repos sampled`);
  console.log(`${formatCount(report.summary.sampledPrs)} PRs and ${formatCount(report.summary.sampledCommits)} commits scanned`);
}

if (require.main === module) {
  main().catch(error => {
    console.error(error);
    process.exit(1);
  });
}

module.exports = {
  DEFAULT_COHORT,
  analyzeTextEvidence,
  classifyRepoEvidence,
  renderHtml,
  scoreRepoEvidence,
  summarizeCommits,
  summarizePullRequests,
};
